service: aurumfit-kiran
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
plugins:
  - serverless-webpack
custom:
  webpack:
    includeModules: true